INSERT INTO tb_especialidade (nome, descricao) VALUES ('Alergia e imunologia', 'é a área que trata de invasores alérgenos e as formas de defesa do organismo.');
INSERT INTO tb_especialidade (nome, descricao) VALUES ('Anestesiologia', 'cuida da aplicação de anestésicos e analgésicos em procedimentos e do manejo da dor.');
INSERT INTO tb_especialidade (nome, descricao) VALUES ('Cardiologia', 'responsável pela realização de procedimentos cirúrgicos em diferentes partes do corpo.');
INSERT INTO tb_especialidade (nome, descricao) VALUES ('Clínica médica', 'responsável pela realização de procedimentos cirúrgicos em diferentes partes do corpo.');
INSERT INTO tb_especialidade (nome, descricao) VALUES ('Dermatologia', 'trata de doenças da pele e seus anexos.');
INSERT INTO tb_endereco (rua, numero, complemento, bairro, cep, cidade, estado) VALUES ('Rua XV de Novembro', '345', 'N/A', 'Centro', '91333-568', 'Porto Alegre', 'RS');
INSERT INTO tb_endereco (rua, numero, complemento, bairro, cep, cidade, estado) VALUES ('Av. Fortaleza', '1002', 'N/A', 'Centro', '91133-254', 'Gravataí', 'RS');
INSERT INTO tb_endereco (rua, numero, complemento, bairro, cep, cidade, estado) VALUES ('Rua dos Alcântaras', '25', 'sala 3652', 'Centro', '97654-764', 'Cachoeirinha', 'RS');
INSERT INTO tb_endereco (rua, numero, complemento, bairro, cep, cidade, estado) VALUES ('Rua João Saldanha', '659', 'N/A', 'Centro', '93234-240', 'Guaíba', 'RS');
INSERT INTO tb_endereco (rua, numero, complemento, bairro, cep, cidade, estado) VALUES ('Av. do Parque', '477', 'N/A', 'Centro', '91233-110', 'Porto Alegre', 'RS');
INSERT INTO tb_medico (nome, email, crm, atende_convenio, id_especialidade) VALUES ('Fábio Knost', 'fknost@gmail.com', 'CRM 21458 RS', true, 4);
INSERT INTO tb_medico (nome, email, crm, atende_convenio, id_especialidade) VALUES ('Beatriz Pacheco', 'biapacheco@gmail.com', 'CRM 11254 RS', true, 5);
INSERT INTO tb_medico (nome, email, crm, atende_convenio, id_especialidade) VALUES ('Silvia Botelho', 'drasilviabotelho@gmail.com', 'CRM 16225 RS', false, 2);
INSERT INTO tb_medico (nome, email, crm, atende_convenio, id_especialidade) VALUES ('Flavio Moreira', 'drmoreira@gmail.com', 'CRM 12232 RS', false, 1);
INSERT INTO tb_paciente (nome, cpf, sexo, email, data_cadastro, id_endereco) VALUES ('Betina Brenda Alana da Silva', '394.718.750-56', 'FEMININO', 'betina_brenda@gmail.com', TIMESTAMP WITH TIME ZONE '2022-04-03 10:00:00', 2);
INSERT INTO tb_paciente (nome, cpf, sexo, email, data_cadastro, id_endereco) VALUES ('Manuela Sophie Manuela', '619.725.520-07', 'FEMININO', 'manuelas@gmail.com', TIMESTAMP WITH TIME ZONE '2021-12-11T14:00:00Z', 1);
INSERT INTO tb_paciente (nome, cpf, sexo, email, data_cadastro, id_endereco) VALUES ('Filipe Mário da Silva', '185.384.300-84', 'MASCULINO', 'fmario@gmail.com', TIMESTAMP WITH TIME ZONE '2022-09-01T15:45:00Z', 2);
INSERT INTO tb_paciente (nome, cpf, sexo, email, data_cadastro, id_endereco) VALUES ('Paulo Márcio da Costa', '974.463.280-10', 'MASCULINO', 'pmcosta@gmail.com', TIMESTAMP WITH TIME ZONE '2020-11-05T17:10:00Z', 3);
INSERT INTO tb_paciente (nome, cpf, sexo, email, data_cadastro, id_endereco) VALUES ('Fernando Lorenzo Galvão', '378.943.810-39', 'MASCULINO', 'flg25@gmail.com', TIMESTAMP WITH TIME ZONE '2021-02-23T08:45:00Z', 1);
INSERT INTO tb_funcionario (nome, cpf, email, id_endereco) VALUES ('Ayrton Senna', '449.616.740-95', 'senna@gmail.com', 4);
INSERT INTO tb_funcionario (nome, cpf, email, id_endereco) VALUES ('Alain Prost', '273.644.930-42', 'prost@gmail.com', 5);
INSERT INTO tb_funcionario (nome, cpf, email, id_endereco) VALUES ('Rubens Barrichello', '702.392.820-00', 'barrichello@gmail.com', 5);
INSERT INTO tb_funcionario (nome, cpf, email, id_endereco) VALUES ('Michael Schumacher', '881.269.610-40', 'schumacher@gmail.com', 4);
INSERT INTO tb_funcionario (nome, cpf, email, id_endereco) VALUES ('Nelson Piquet', '343.277.680-22', 'piquet@gmail.com', 1);